### ISSUE TITLE
Allow to add key/value pairs to a socket i.e. a socket scope

### ISSUE THREAD

**Issue by flowersinthesand** [cettia/cettia-java-server#22]
Basically, it is analogous to the request scope defined in Servlet specification so that this attribute set should be initialized and destroyed along with the lifecycle of the socket.

- [x] Implement `<T> T get(String name)` in `ServerSocket`

It should return the value mapped to the given name.

- [x] Implement `ServerSocket socket.set(String name, Object value)`

It should associate the value with the given name.

- [x] Implement `ServerSocket socket.remove(String name)`

It should remove the value associated with the given name.

Furthermore, we can this attributes to manipulate a selection for socket delicately i.e. Sentence like `server.all().has("is-admin", true).send("foo", "bar")`.

See the discussion at https://groups.google.com/d/topic/cettia/xAzTTqfY4FQ/discussion

**Comment by ralscha** [comment]
I like the `has` method, that could be useful. What do you think about a negate function?
```
server.all().has("is-admin", true).not().send("foo", "bar")
```

Maybe the same for tags
```
server.byTag("tag").not().send("foo", "bar");
```

Don't have an use case for that. Just thinking that could be useful.

**Comment by ralscha** [comment]
Maybe an easier approach is to provide one method that takes a `java.util.function.Predicate` implementation as argument. 
```
server.select(socket -> socket.get("is-admin") == null).send("foo", "bar");
```
This way a developer can implement more complex filters.

**Comment by flowersinthesand** [comment]
> What do you think about a negate function?

Great. Furthermore, we could be inspired by fluent interfaces like Spring's RequestPredicates and CSS selectors.

> Maybe an easier approach is to provide one method that takes a java.util.function.Predicate implementation as argument.

👍 Yeah, it's absolutely great. We can do this in Cettia 2 since Cettia 1 is supposed to support Java 7. This feature including socket matching operations will be one of the core features of Cettia 2.

**Comment by ralscha** [comment]
You could backport the Predicate interface to Java 7.

````
public interface ServerSocketPredicate {
    boolean test(ServerSocket socket);	
}
````

Somebody working on Java 7 can use anonymous inner classes or implementations of the interface.
```
  server.select(new ServerSocketPredicate() {			
	@Override
	public boolean test(ServerSocket socket) {
	   return socket.tags().contains("tag1") && !socket.tags().contains("tag2");
	}
  }).send("foo", "bar");
```

Projects with Java 8 and Cettia 1.1 can use a lambda or an adapter if they want to use java.util.function.Predicate

```
server.select(socket -> socket.tags().contains("tag1") && !socket.tags().contains("tag2"))
          .send("foo", "bar");
```

```
  Predicate<ServerSocket> p1 = socket -> socket.tags().contains("tag1");
  Predicate<ServerSocket> p2 = socket -> socket.tags().contains("tag2");		
  server.select(adapt(p1.and(p2.negate()))).send("foo", "bar");

  ServerSocketPredicate adapt(Predicate<ServerSocket> predicate) {
      return socket -> predicate.test(socket);
  }
```

If Cettia 2 moves from ServerSocketPredicate to Predicate, upgrading a project is easy. If the project only uses lambas they don't have to change anything and in the second case they have to remove the adapt method.

**Comment by flowersinthesand** [comment]
I think `ServerSocketPredicate` should extend `Serializable` for clustered environment, and then everything will be okay. Thanks for the suggestion.

**Comment by flowersinthesand** [comment]
@ralscha Inspired by your solution, I created some issues #23 #24 #25 to support "select some sockets and do something with them" intuitively, which is the basic concept of Cettia. It would be nice if you could review them when you get a chance.

**Comment by flowersinthesand** [comment]
* [ ] Write unit tests - it's time to expose DefaultServer.DefaultServerSocket in some way.
