### ISSUE TITLE
Add an Action interface extending Serializable

### ISSUE THREAD

**Issue by flowersinthesand** [cettia/cettia-java-server#23]
Asity's Action is not serializable, and not compatible with clustered environments. The current solution is either writing a class implementing Action and Serializable like the [SendAction](https://github.com/cettia/cettia-java-server/blob/84c0b702b55141773bf5fab3f0cf06b9a4585597/server/src/main/java/io/cettia/Sentence.java#L73) in Sentence or using cast expressions of Java 8 like `(Action<ServerSocket> & Serializable) socket -> {}`.

With `SerializableAction`, we can allow to use plain lambdas without using cast expressions.

* [x] Write a `io.cettia.SerializableAction` and replace Sentence's private interface of the same name with this one.

It is an `io.cettia.asity.action.Action` that extends `Serializable`. BTW, we could add this serialized version to Asity like `io.cettia.asity.action.SerializableAction` too and use it in Cettia 2?.

* Replace method signatures whose arguments are supposed to be serialized
  * [x] `Server all(SerializableAction<ServerSocket> action)`
  * [x] `Server byTag(SerializableAction<ServerSocket> action)`

This breaks the backward compatibility but I think it would be fine because the recommended usage has been using `Sentence` and using lambda is not the case.

**Comment by ralscha** [comment]
I don't have any experience with clusters, but couldn't you get rid of `java.ioSerializable` and use a serialization library like [Kryo](https://github.com/EsotericSoftware/kryo). 
Kryo is able to serialize and deserialize any java object without any special marker interface.

**Comment by flowersinthesand** [comment]
In fact, Cettia doesn't get involved in how actions should be serialized and transmitted to other nodes, and it's up to users. To support users who don't want to use Kyro for whatever reason, I think it's safe to implement Serializable but admit that there has not been enough feedback.

BTW, Kyro seems to be a good alternative for Java's built-in serialization mechanism. I would like to use it if I get a chance.
